// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 16.6.2014 - 16:14
// Table create Date : 6.12.2013 - 16:48
// Table Description : 

using Core.Entities;
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace Entities.ErcanProduct.Concrete.Contact
{
    [Serializable,DataContract]
	public partial class Account : IEntity
	{

         
	}
}
