// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 16.6.2014 - 16:14
// Table create Date : 6.12.2013 - 16:48
// Table Description : 

using Entities.Concrete.DomainObjects;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
namespace Entities.ErcanProduct.Concrete.Contact
{

    [Table("Account", Schema = "FINANCE")]
    public partial class Account : DomainObjectBase
    {
        [Key,DataMember]
        public int AccountId { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "")]
        [MaxLength(25, ErrorMessage = ""),DataMember]
        public string AccountNumber { get; set; }

        [DataMember]
        public int CompanyId { get; set; }

        [DataMember]
        public int ContactId { get; set; }

        [DataMember]
        public bool? IsDeleted { get; set; }
    }
}
