// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 13.6.2014 - 08:54
// Table create Date : 10.6.2014 - 14:58
// Table Description : 

using System;
using System.Runtime.Serialization;

namespace Entities.ErcanProduct.Concrete.Contact
{
    [Serializable]
    [DataContract]
	public partial class Bank 
	{
        public override string ToString()
        {
            return Name;
        }
	}
}
