// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 13.6.2014 - 08:54
// Table create Date : 10.6.2014 - 14:58
// Table Description : 

using Entities.Concrete.DomainObjects;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
namespace Entities.ErcanProduct.Concrete.Contact
{
    [Table("Bank", Schema = "COMMON")]
	public partial class Bank: DomainObjectBase
	{
		[Key]
        [DataMember]
		public int BankId{get;set;}

		
		[Required(AllowEmptyStrings = false, ErrorMessage = "")]
		[MaxLength(4, ErrorMessage = "")]
        [DataMember]
        public string BankCode{get;set;}

		
		[Required(AllowEmptyStrings = false, ErrorMessage = "")]
		[MaxLength(100, ErrorMessage = "")]
        [DataMember]
        public string Name{get;set;}


        [DataMember]
        public bool? IsDeleted{get;set;}

	}
}
