// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 13.6.2014 - 08:54
// Table create Date : 10.6.2014 - 14:25
// Table Description : 

using Entities.Concrete.DomainObjects;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Entities.ErcanProduct.Concrete.Contact
{
    [Table("BankBranch", Schema = "COMMON")]
	public partial class BankBranch: DomainObjectBase
	{
		[Key]
		public int BankBranchId{get;set;}

		
		public int? BankId{get;set;}

		
		[MaxLength(6, ErrorMessage = "")]
		public string BranchCode{get;set;}

		
		public int? CityId{get;set;}

		
		[MaxLength(100, ErrorMessage = "")]
		public string BranchName{get;set;}

		
		[MaxLength(100, ErrorMessage = "")]
		public string Adres{get;set;}

		
		[MaxLength(11, ErrorMessage = "")]
		public string Tel{get;set;}

		
		[MaxLength(15, ErrorMessage = "")]
		public string SwiftCode{get;set;}

		
		public bool? IsDeleted{get;set;}


	}
}
