// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 13.6.2014 - 08:54
// Table create Date : 10.6.2014 - 14:25
// Table Description : 

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities.ErcanProduct.Concrete.Contact
{
    [Serializable]
	public partial class BankBranch 
	{
        public override string ToString()
        {
            //if (Bank != null)
            //{
            //    return Bank.BankCode + "-" + Bank.Name + "-" + BranchCode  +"-" + BranchName;
            //}
            //else
            //{
            //    return BranchName;
            //}
            return BranchName;
        }

        [ForeignKey("BankId")]
	    public Bank Bank { get; set; }

        [ForeignKey("CityId")]
        public City City { get; set; }

        //[NotMapped]
        //public string BankCode { get; set; }
	}
}
