// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 14.2.2015 - 11:08
// Table create Date : 14.2.2015 - 11:03
// Table Description : 

using Core.Entities;
using System;

namespace Entities.ErcanProduct.Concrete.Contact
{
    [Serializable]
	public partial class ContactMilesCardType : IEntity
	{

	}
}
