// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 10.7.2014 - 09:37
// Table create Date : 10.7.2014 - 08:19
// Table Description : 

using Core.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace Entities.ErcanProduct.Concrete.Contact
{
    [Serializable] 
    public partial class ContactRelation : IEntity
    {
        public ContactRelation()
        {

        }
        [ForeignKey("FromContactId")]
        public Contact FromContact { get; set; }

        [ForeignKey("ToContactId")]
        public Contact ToContact { get; set; }

        [ForeignKey("FromRelationTypeId")]
        public ContactRelationType FromRelationType { get; set; }

        [ForeignKey("ToRelationTypeId")]
        public ContactRelationType ToRelationType { get; set; }

        [NotMapped]
        public string ContactName { get; set; }

        [NotMapped]
        public string RelationName { get; set; }

        [NotMapped]
        public string Guid { get; set; }

        [NotMapped, DataMember]
        public int? StateId { get; set; }
    }
}
