// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 15.10.2014 - 09:59
// Table create Date : 13.10.2014 - 13:44
// Table Description : 


using Core.Entities;
using System.ComponentModel.DataAnnotations.Schema;
//using con=Entities.Concrete;

namespace Entities.ErcanProduct.Concrete.Contact
{
	public partial class ContactAjandaContact : IEntity
	{
        [ForeignKey("ContactId")]
        public Contact Contact { get; set; } 
	}
}
