// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 15.10.2014 - 09:59
// Table create Date : 15.10.2014 - 08:40
// Table Description : 

using Core.Entities;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities.ErcanProduct.Concrete.Contact
{
	public partial class ContactAjandaAgency : IEntity
	{  

	}
}
