// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 15.10.2014 - 09:58
// Table create Date : 13.10.2014 - 13:44
// Table Description : 

using Core.Entities;
using System.Collections.Generic;

namespace Entities.ErcanProduct.Concrete.Contact
{
    public partial class ContactAjanda : IEntity
    {
        public ContactAjanda()
        {
            ContactAjandaContacts = new List<ContactAjandaContact>();
            ContactAjandaAgencys = new List<ContactAjandaAgency>();
        }

        public List<ContactAjandaContact> ContactAjandaContacts { get; set; }

        public List<ContactAjandaAgency> ContactAjandaAgencys { get; set; }

    }
}
