// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 15.10.2014 - 09:58
// Table create Date : 13.10.2014 - 13:44
// Table Description : 

using Entities.Concrete.DomainObjects;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Entities.ErcanProduct.Concrete.Contact
{
    [Table("ContactAjanda", Schema = "CONTACT")]
	public partial class ContactAjanda: DomainObjectBase
	{
		[Key]
		public int ContactAjandaId{get;set;}
		 
		public DateTime StartDate{get;set;}

        public DateTime EndDate { get; set; }
		 
		[MaxLength(50, ErrorMessage = "")]
		public string Title{get;set;}
		 
		[MaxLength(500, ErrorMessage = "")]
		public string Description{get;set;}

	    public bool IsAllDay { get; set; }
	    public bool IsEditable { get; set; }
	    public bool IsDeleted { get; set; }
	  
	}
}
