// This file is auto generated by Onder Lop with Entity Creator.
// Class create date : 30.09.2019 - 13:12
// Table create Date : 30.09.2019 - 11:52
// Table Description : 

using Entities.Concrete.DomainObjects;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Entities.ErcanProduct.Concrete.Contact
{
    [Table("ContactChat", Schema = "CONTACT")]
	public partial class ContactChat: DomainObjectBase
	{
		[Key]
		public int ContactChatId{get;set;}


		public int ContactId{get;set;}

		[MaxLength(50)]
		public string SourceAppName{get;set;}

        [MaxLength(50)]
        public string ChatSource { get; set; }

        public int? ChatSessionId{get;set;}

   
		public DateTime? DateTime{get;set;}


		public string Message{get;set;}

      
		public int? AgentId{get;set;}

	
		[MaxLength(50)]
		public string AgentFullName{get;set;}

		
		public int? AgencyPersonContactId{get;set;}

	
		[MaxLength(50)]
		public string VisitorFullName { get;set;}



	}
}
