// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 14.2.2015 - 11:08
// Table create Date : 14.2.2015 - 11:03
// Table Description : 

using Entities.Concrete.DomainObjects;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
namespace Entities.ErcanProduct.Concrete.Contact
{
    [Table("ContactMilesCardType", Schema = "CONTACT"),DataContract]
	public partial class ContactMilesCardType: DomainObjectBase
	{
		[Key, DataMember]
		public int ContactMilesCardTypeId { get; set; }

		[DataMember]
		public int? ContactId { get; set; }

		[DataMember]
		public int? MilesCardTypeId { get; set; }
		[DataMember]
		public string Number { get; set; }
	}
}
