// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 10.7.2014 - 09:38
// Table create Date : 10.7.2014 - 08:19
// Table Description : 

using Entities.Concrete.DomainObjects;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
namespace Entities.ErcanProduct.Concrete.Contact
{
    [Table("ContactRelationType", Schema = "CONTACT"),DataContract]
	public partial class ContactRelationType: DomainObjectBase
	{
		[Key,DataMember]
        public int ContactRelationTypeId { get; set; }

		
		[Required(AllowEmptyStrings = false, ErrorMessage = "")]
		[MaxLength(50, ErrorMessage = ""),DataMember]
		public string RelationName{get;set;}

		
		public bool? IsDeleted{get;set;}

	}
}
