// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 10.7.2014 - 09:39
// Table create Date : 10.7.2014 - 08:19
// Table Description : 

using Core.Entities;

namespace Entities.ErcanProduct.Concrete.Contact
{
	public partial class ContactRelationTypeT : IEntity
	{

	}
}
