// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 13.6.2014 - 08:38
// Table create Date : 10.6.2014 - 14:26
// Table Description : 

using Core.Entities;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace Entities.ErcanProduct.Concrete.Contact
{
    [DataContract]
	public partial class ContactBank : IEntity
    {
        [ForeignKey("UnitId")]
        [DataMember]
	    public Unit Unit { get; set; }
        [ForeignKey("BankBranchId")]
        [DataMember]
        public BankBranch BankBranch { get; set; }

        [ForeignKey("BankId")]
        [DataMember]
        public Bank Bank { get; set; } 
        public Contact Contact { get; set; }
    }
}
