// This file is auto generated by Batuhan Öztürk with Entity Creator.
// Class create date : 10.7.2014 - 09:38
// Table create Date : 10.7.2014 - 08:19
// Table Description : 

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
namespace Entities.ErcanProduct.Concrete.Contact
{
    [Table("ContactRelationType_T", Schema = "CONTACT"),DataContract]
	public partial class ContactRelationTypeT: BaseTranslateEntity
	{
		[Key,DataMember]
        public int ContactRelationTypeTId { get; set; }

		[DataMember]
        public int? ContactRelationTypeId { get; set; }

		
		[MaxLength(50, ErrorMessage = ""),DataMember]
		public string RelationName{get;set;}

	}
}
