// This file is auto generated by Onder Lop with Entity Creator.
// Class create date : 30.09.2019 - 13:12
// Table create Date : 30.09.2019 - 11:52
// Table Description : 

using Core.Entities;

namespace Entities.ErcanProduct.Concrete.Contact
{
    public partial class ContactChat : IEntity
	{

	}
}
