// This file is auto generated by Erol Yaldır with Entity Creator.
// Class create date : 13.8.2014 - 13:29
// Table create Date : 18.7.2014 - 15:03
// Table Description : 

using Core.Entities;
using System;
using System.Collections.Generic;

namespace Entities.ErcanProduct.Concrete.Contact
{
    [Serializable]
    public partial class MilesCardType : IEntity
    {
        public MilesCardType()
        {
            Translate = new List<MilesCardTypeT>();
        }
        public ICollection<MilesCardTypeT> Translate { get; set; }
        public override string ToString()
        {
            return this.Name;
        }
    }
}
