// This file is auto generated by Erol Yaldır with Entity Creator.
// Class create date : 13.8.2014 - 13:29
// Table create Date : 18.7.2014 - 15:03
// Table Description : 

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Entities.ErcanProduct.Concrete.Contact
{
    [Table("MilesCardType_T", Schema = "FLIGHT")]
	public partial class MilesCardTypeT: BaseTranslateEntity
	{
		[Key]
		public int MilesCardTypeTId{get;set;}
         
		[MaxLength(50, ErrorMessage = "")]
		public string Name{get;set;}
         
		public int MilesCardTypeId{get;set;}




	}
}
