// This file is auto generated by Sadık Kahveci with Entity Creator.
// Class create date : 1.11.2017 - 14:42
// Table create Date : 1.11.2017 - 10:13
// Table Description : 

using Entities.Concrete.DomainObjects;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace Entities.ErcanProduct.Concrete.Contact
{
    [Table("PnrPassenger", Schema = "FLIGHT"),DataContract]
	public partial class PnrPassenger: DomainObjectBase
	{
		[Key,DataMember]
		public int PNRPassengerId{get;set;}

		[MaxLength(15, ErrorMessage = ""), DataMember]
		public string TicketNumber{get;set;}

		[MaxLength(100, ErrorMessage = ""), DataMember]
		public string Name{get;set;}

		[MaxLength(200, ErrorMessage = ""), DataMember]
		public string Surname{get;set;}
        [DataMember]
		public decimal LandingTax{get;set;}
	    [DataMember]
        public decimal FuelTax{get;set;}
	    [DataMember]
        public decimal OtherServiceFee{get;set;}
	    [DataMember]
        public int? PassengerType{get;set;}
	    [DataMember]
        public decimal BaseFare{get;set;}
	    [DataMember]
        public decimal Tax{get;set;}
	    [DataMember]
        public decimal ServiceFee{get;set;}
	    [DataMember]
        public decimal TotalFare{get;set;}
	    [DataMember]
        public decimal CurrencyValue{get;set;}
	    [DataMember]
        [MaxLength(3, ErrorMessage = "")]
		public string CurrencyType{get;set;}
	    [DataMember]
        [MaxLength(10, ErrorMessage = "")]
	    public string Pnr { get; set; }
	    [DataMember]
        public int PnrSegmentId { get; set; }
	    [DataMember]
        public string PassengerTitle { get; set; }
	    [DataMember]
        public decimal AgencyFee { get; set; }
	    [DataMember]
        public decimal RealAgencyFee { get; set; }
        [DataMember]
        public decimal PurchaseFee { get; set; }
	    [DataMember]
        public decimal PurchasedServiceFee { get; set; }
	    [DataMember]
        public decimal PurchasedOtherServiceFee { get; set; }
	    [DataMember]
        public decimal PersonalFee { get; set; }

        [DataMember]
        public decimal OwnFee { get; set; }

        [DataMember]
        public decimal RealPersonalFee { get; set; }
	    [DataMember]
        public DateTime? TicketDate { get; set; }

        [DataMember]
        public string FullPhone { get; set; }
    }
}
