// This file is auto generated by Can Akkaya with Entity Creator.
// Class create date : 1.11.2017 - 14:42
// Table create Date : 1.11.2017 - 10:13
// Table Description : 

using Core.Entities;

namespace Entities.ErcanProduct.Concrete.Contact
{
	public partial class PnrPassenger : IEntity
	{

	}
}
