// This file is auto generated by Sadık Kahveci with Entity Creator.
// Class create date : 1.11.2017 - 14:57
// Table create Date : 31.10.2017 - 14:39
// Table Description : 

using Entities.Concrete.DomainObjects;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace Entities.ErcanProduct.Concrete.Contact
{
    [Table("PNRSegment", Schema = "FLIGHT"), DataContract]
    public partial class PnrSegment : DomainObjectBase
    {
        [Key, DataMember]
        public int PnrSegmentId { get; set; }

        [MaxLength(10, ErrorMessage = ""), DataMember]
        public string FlightNumber { get; set; }

        [DataMember]
        public string CabinClass { get; set; }

        [MaxLength(3, ErrorMessage = ""), DataMember]
        public string DepartureLocationCode { get; set; }
        [DataMember]
        public DateTime? DepartureDate { get; set; }

        [MaxLength(3, ErrorMessage = ""), DataMember]
        public string ArrivalLocationCode { get; set; }
        [DataMember]
        public DateTime? ArrivalDate { get; set; }

        [MaxLength(10, ErrorMessage = ""), DataMember]
        public string Pnr { get; set; }
        [DataMember]
        public int TicketedReservationPnrId { get; set; }
    }
}
