// This file is auto generated by Sadık Kahveci with Entity Creator.
// Class create date : 1.11.2017 - 14:57
// Table create Date : 31.10.2017 - 14:39
// Table Description : 

using Core.Entities;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace Entities.ErcanProduct.Concrete.Contact
{
    public partial class PnrSegment : IEntity
    {
        [ForeignKey("PnrSegmentId"), DataMember]
        public List<PnrPassenger> PnrPassengers { get; set; }
    }
}
