//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Concrete.DomainObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CityResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CityResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Entities.Concrete.DomainObjects.Resources.CityResource", typeof(CityResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir kodu 3 karakterden fazla olamaz..
        /// </summary>
        internal static string CityCodeMaxLength {
            get {
                return ResourceManager.GetString("CityCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir kodu gerekli..
        /// </summary>
        internal static string CityCodeRequired {
            get {
                return ResourceManager.GetString("CityCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kodu başka bir kayıt tarafından kullanılmaktadır..
        /// </summary>
        internal static string CityCodeUsing {
            get {
                return ResourceManager.GetString("CityCodeUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir adı 50 karakterden fazla olamaz..
        /// </summary>
        internal static string CityNameMaxLength {
            get {
                return ResourceManager.GetString("CityNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir adı gerekli..
        /// </summary>
        internal static string CityNameRequired {
            get {
                return ResourceManager.GetString("CityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adı başka bir kayıt tarafından kullanılmaktadır..
        /// </summary>
        internal static string CityNameUsing {
            get {
                return ResourceManager.GetString("CityNameUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaka kodu 3 karakterden fazla olamaz..
        /// </summary>
        internal static string PlateCodeMaxLength {
            get {
                return ResourceManager.GetString("PlateCodeMaxLength", resourceCulture);
            }
        }
    }
}
